### ISSUE TITLE
android 调js函数无法直接传递json对象

### ISSUE THREAD

**Issue by dielian-wizard-ly** [wragony/Android-JsBridge#3]
```
jsBridge.callJs("test", jbMap.convertJS(), new OnValueCallback() {
                    @Override
                    public void onCallBack(String data) {
                        Log.d(JsBridge.TAG, "onCallBack:data=" + data);
                        Toast.makeText(X5WebViewActivity.this, "接收: "+data, Toast.LENGTH_SHORT).show();
                    }
                });
```

**Comment by wragony** [comment]
**com.wragony.android.jsbridge.JsBridge 里增加了一个重载方法：**
`
public abstract void callJs(String functionName, JsObject params, OnValueCallback mCallback);
`

**Comment by wragony** [comment]
> ```
> jsBridge.callJs("test", jbMap.convertJS(), new OnValueCallback() {
>                     @Override
>                     public void onCallBack(String data) {
>                         Log.d(JsBridge.TAG, "onCallBack:data=" + data);
>                         Toast.makeText(X5WebViewActivity.this, "接收: "+data, Toast.LENGTH_SHORT).show();
>                     }
>                 });
> ```

**com.wragony.android.jsbridge.JsBridge 里增加了一个重载方法：**
`
public abstract void callJs(String functionName, JsObject params, OnValueCallback mCallback);

`
